# Generated by Django 5.2.4 on 2025-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('w2', 'W2'), ('contract', 'Contract')], max_length=20),
        ),
    ]
