# Generated by Django 5.2 on 2025-07-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meetingremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingremark',
            name='participant',
        ),
    ]
