# Generated by Django 5.2 on 2025-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_meetingremark_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='jb_link',
            field=models.URLField(blank=True, help_text='Link to job description or job board', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='remarks',
            field=models.TextField(blank=True, help_text='General meeting remarks from any participant', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='resume_link',
            field=models.URLField(blank=True, help_text='Link to resume or document', null=True),
        ),
        migrations.DeleteModel(
            name='MeetingRemark',
        ),
    ]
