# Generated by Django 5.2 on 2025-07-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meeting_jb_link_meeting_remarks_meeting_resume_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='jb_link',
            new_name='jd_link',
        ),
    ]
