# Generated by Django 5.2.4 on 2025-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_jb_link_meeting_jd_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
