# Generated by Django 5.2.4 on 2025-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_token_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
